Change src manager to git

diff --git a/bin/php-nabe b/bin/php-nabe
--- a/bin/php-nabe
+++ b/bin/php-nabe
@@ -17,7 +17,7 @@ function isInstalled() {
 
 function getCurrentVersion() {
     if [ ! -f $PVM_PATH/current ]; then
-        return -1;
+        return 1;
     fi
 
     cat $PVM_PATH/current
@@ -28,32 +28,19 @@ function downloadSrc() {
         mkdir $PVM_PATH/src
     fi
 
-    if [ ! -d $PVM_PATH/downloads ]; then
-        mkdir $PVM_PATH/downloads
+    if [ ! -d $PVM_PATH/src/php-src ]; then
+        git clone https://github.com/php/php-src.git
     fi
 
-    if [ ! -d $PVM_PATH/downloads/tmp ]; then
-        mkdir $PVM_PATH/downloads/tmp
+    cd $PVM_PATH/src/php-src
+    git clean -fd
+
+    git checkout php-$1
+
+    if [ $? -ne 0 ]; then
+        echo "[ERR] could't download sourcecode."
+        return 1;
     fi
-
-    cd $PVM_PATH/downloads
-
-    if [ ! -f php-$1.tar.gz ]; then
-
-        URL="https://github.com/php/php-src/tarball/php-$2"
-        curl -L -# -o php-$1.tar.gz.tmp $URL
-
-        if [ $? -ne 0 ]; then
-            echo "[ERR] could't download sourcecode."
-            return -1;
-        fi
-
-        mv php-$1.tar.gz.tmp php-$1.tar.gz
-
-    fi
-
-    tar zxvf $PVM_PATH/downloads/php-$1.tar.gz -C $PVM_PATH/downloads/tmp
-    mv $PVM_PATH/downloads/tmp/php-php-src-* $PVM_PATH/src/php-$1
 
     return 0;
 }
@@ -73,9 +60,47 @@ function php-nabe() {
             exit 1;
         fi
 
-        downloadSrc $2
+        # install autoconf-2.59d
+        if [ ! -d $PVM_PATH/build/autoconf-2.59d ]; then
+            cd $PVM_PATH/src
+            if [ ! -d $PVM_PATH/src/autoconf ]; then
+                git clone git://git.sv.gnu.org/autoconf
+            fi
+            cd autoconf
 
-        cd $PVM_PATH/src/php-$2
+            git clean -df
+            git checkout AUTOCONF-2.59d
+            if [ $? -ne 0 ]; then
+                echo "failed to checkout autoconf-2.59d"
+                exit 1;
+            fi
+
+
+            ./configure --prefix=$PVM_PATH/build/autoconf-2.59d
+            if [ $? -ne 0 ]; then
+                echo "failed to configure"
+                exit 1;
+            fi
+
+            make
+            if [ $? -ne 0 ]; then
+                exit 1;
+            fi
+
+            make install
+            if [ $? -ne 0 ]; then
+                exit 1;
+            fi
+        fi
+
+        downloadSrc $2
+        if [ $? -ne 0 ]; then
+            exit 1;
+        fi
+
+        export PHP_AUTOCONF=$PVM_PATH/build/autoconf-2.59d/bin/autoconf
+
+        cd $PVM_PATH/src/php-src
         ./buildconf --force
         if [ $? -ne 0 ]; then
             exit 1;
@@ -87,8 +112,6 @@ function php-nabe() {
             exit 1;
         fi
 
-        make distclean
-
         make
         if [ $? -ne 0 ]; then
             exit 1;
@@ -99,7 +122,7 @@ function php-nabe() {
             exit 1;
         fi
 
-        cp $PVM_PATH/src/php-$2/php.ini-development $PREFIX/etc/php.ini
+        cp $PVM_PATH/src/php-src/php.ini-development $PREFIX/etc/php.ini
 
         echo $2 >> $PVM_PATH/installed
 
@@ -146,12 +169,15 @@ function php-nabe() {
         $PVM_PATH/build/php-$version/bin/php $PVM_PATH/lib/checkext.php $2
         if [ $? -eq 0 ]; then
             echo "You installed $2 extension already."
-            exit 0
+            exit 1
         fi
 
         downloadSrc $version
+        if [ $? -ne 0 ]; then
+            exit 1;
+        fi
 
-        cd $PVM_PATH/src/php-$version
+        cd $PVM_PATH/src/php-src
 
         if [ -d ext/$2 ]; then
             # ext
